name: Daily Traffic Collecting

on:
  schedule:
    - cron: '*/15 6-8 * * *'
    - cron: '*/15 11-12 * * *'
    - cron: '*/15 16-17 * * *'
  workflow_dispatch:

jobs:
  traffic_data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Collecting traffic data
        run: python core/etl.py
        env:
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_NAME: ${{ secrets.DB_NAME }}
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASS: ${{ secrets.DB_PASS }}
          DB_PORT: ${{ secrets.DB_PORT }}
          TRAFFIC_API_KEY: ${{ secrets.TRAFFIC_API_KEY }}
          WEATHER_API_KEY: ${{ secrets.WEATHER_API_KEY }}
